In [80]:
import pandas as pd
import numpy as np

In [81]:
df = pd.read_csv('redfin_usa_properties_dataset_sample.csv')

In [82]:
df.head()

,url,name,price,formatted_price,currency,address,locality,region,postal_code,country,...,longitude,description,baths,beds,sqft,property_details,images,listed_by,uniq_id,scraped_at
0,https://www.redfin.com/SC/EASTOVER/HICKORY-HIL...,Hickory Hill Rd,40000.0,"$40,000",USD,Hickory Hill Rd,Eastover,SC,29044,US,...,-80.681014,This 4.13 ac of wooded land is ready for you b...,-,NaN,-,"[{'Status': 'Active'}, {'Time on Redfin': '230...",NaN,Listed by Glen Levine • Keller Williams Columbia,efb7c6cf-dbb1-5e4e-9028-32bc46800252,17/04/2022 21:21:33
1,https://www.redfin.com/NY/Flushing/147-35-38th...,147-35 38th Ave Unit B37,415000.0,"$415,000",USD,147-35 38th Ave Unit B37,Flushing,NY,11354,US,...,-73.817481,Large and Sunny Two Bedroom Coop Apartment in ...,1,2.0,-,"[{'Status': 'Active'}, {'Time on Redfin': '201...",https://ssl.cdn-redfin.com/photo/269/mbpaddedw...,Listing by Nadine Persaud • All Area Brokerag...,e10a3655-1719-57e7-8d9d-984c82584c73,17/04/2022 21:21:34
2,https://www.redfin.com/TX/Unknown/1024-Indigo-...,1024 Indigo Sky St,240950.0,"$240,950",USD,1024 Indigo Sky St,El Paso,TX,79928,US,...,-106.206967,"The Myrtle by Saratoga Homes. A 1 Story, 4 Bed...",3,4.0,"1,687","[{'Status': 'Pending'}, {'Time on Redfin': '13...",https://ssl.cdn-redfin.com/photo/183/mbpaddedw...,Listed by Octavio Duarte •TREC #0616335 • SITE...,fbadbf86-3ee5-5100-a163-2acd162c43e5,17/04/2022 21:21:34
3,https://www.redfin.com/OR/Redmond/3439-NW-9th-...,3439 NW 9th St,466995.0,"$466,995",USD,3439 NW 9th St,Redmond,OR,97756,US,...,-121.178761,"At 1979 square feet, the Orchard Encore on lot...",2,4.0,"1,979","[{'Status': 'Pending'}, {'Time on Redfin': '12...",https://ssl.cdn-redfin.com/photo/199/mbpaddedw...,Listed by Lexxye Haggard • New Home Star Oreg...,ba379e0c-5517-56a5-bd93-6e9620577ebc,17/04/2022 21:21:35
4,https://www.redfin.com/IL/Chicago/1545-N-Larra...,1545 N Larrabee St Unit 2N,489900.0,"$489,900",USD,1545 N Larrabee St Unit 2N,Chicago,IL,60610,US,...,-87.643162,Spacious Two Bedroom Condo residing in an Inti...,2,2.0,"1,550","[{'Status': 'Active'}, {'Time on Redfin': '17 ...",https://ssl.cdn-redfin.com/photo/68/mbpaddedwi...,Listed by Kieran Conlon • Compass,c22132b1-1809-5428-bd6c-59de7edf3dff,17/04/2022 21:21:35

In [83]:
# df =df.drop(columns = 'url')
df.drop(columns = 'url', inplace =True)
df.head()

,name,price,formatted_price,currency,address,locality,region,postal_code,country,latitude,longitude,description,baths,beds,sqft,property_details,images,listed_by,uniq_id,scraped_at
0,Hickory Hill Rd,40000.0,"$40,000",USD,Hickory Hill Rd,Eastover,SC,29044,US,33.867386,-80.681014,This 4.13 ac of wooded land is ready for you b...,-,NaN,-,"[{'Status': 'Active'}, {'Time on Redfin': '230...",NaN,Listed by Glen Levine • Keller Williams Columbia,efb7c6cf-dbb1-5e4e-9028-32bc46800252,17/04/2022 21:21:33
1,147-35 38th Ave Unit B37,415000.0,"$415,000",USD,147-35 38th Ave Unit B37,Flushing,NY,11354,US,40.764069,-73.817481,Large and Sunny Two Bedroom Coop Apartment in ...,1,2.0,-,"[{'Status': 'Active'}, {'Time on Redfin': '201...",https://ssl.cdn-redfin.com/photo/269/mbpaddedw...,Listing by Nadine Persaud • All Area Brokerag...,e10a3655-1719-57e7-8d9d-984c82584c73,17/04/2022 21:21:34
2,1024 Indigo Sky St,240950.0,"$240,950",USD,1024 Indigo Sky St,El Paso,TX,79928,US,31.714074,-106.206967,"The Myrtle by Saratoga Homes. A 1 Story, 4 Bed...",3,4.0,"1,687","[{'Status': 'Pending'}, {'Time on Redfin': '13...",https://ssl.cdn-redfin.com/photo/183/mbpaddedw...,Listed by Octavio Duarte •TREC #0616335 • SITE...,fbadbf86-3ee5-5100-a163-2acd162c43e5,17/04/2022 21:21:34
3,3439 NW 9th St,466995.0,"$466,995",USD,3439 NW 9th St,Redmond,OR,97756,US,44.292202,-121.178761,"At 1979 square feet, the Orchard Encore on lot...",2,4.0,"1,979","[{'Status': 'Pending'}, {'Time on Redfin': '12...",https://ssl.cdn-redfin.com/photo/199/mbpaddedw...,Listed by Lexxye Haggard • New Home Star Oreg...,ba379e0c-5517-56a5-bd93-6e9620577ebc,17/04/2022 21:21:35
4,1545 N Larrabee St Unit 2N,489900.0,"$489,900",USD,1545 N Larrabee St Unit 2N,Chicago,IL,60610,US,41.910518,-87.643162,Spacious Two Bedroom Condo residing in an Inti...,2,2.0,"1,550","[{'Status': 'Active'}, {'Time on Redfin': '17 ...",https://ssl.cdn-redfin.com/photo/68/mbpaddedwi...,Listed by Kieran Conlon • Compass,c22132b1-1809-5428-bd6c-59de7edf3dff,17/04/2022 21:21:35

In [84]:
#df= df.drop(columns =['latitude','longitude','images'])
df.head(10)

,name,price,formatted_price,currency,address,locality,region,postal_code,country,latitude,longitude,description,baths,beds,sqft,property_details,images,listed_by,uniq_id,scraped_at
0,Hickory Hill Rd,40000.0,"$40,000",USD,Hickory Hill Rd,Eastover,SC,29044,US,33.867386,-80.681014,This 4.13 ac of wooded land is ready for you b...,-,NaN,-,"[{'Status': 'Active'}, {'Time on Redfin': '230...",NaN,Listed by Glen Levine • Keller Williams Columbia,efb7c6cf-dbb1-5e4e-9028-32bc46800252,17/04/2022 21:21:33
1,147-35 38th Ave Unit B37,415000.0,"$415,000",USD,147-35 38th Ave Unit B37,Flushing,NY,11354,US,40.764069,-73.817481,Large and Sunny Two Bedroom Coop Apartment in ...,1,2.0,-,"[{'Status': 'Active'}, {'Time on Redfin': '201...",https://ssl.cdn-redfin.com/photo/269/mbpaddedw...,Listing by Nadine Persaud • All Area Brokerag...,e10a3655-1719-57e7-8d9d-984c82584c73,17/04/2022 21:21:34
2,1024 Indigo Sky St,240950.0,"$240,950",USD,1024 Indigo Sky St,El Paso,TX,79928,US,31.714074,-106.206967,"The Myrtle by Saratoga Homes. A 1 Story, 4 Bed...",3,4.0,"1,687","[{'Status': 'Pending'}, {'Time on Redfin': '13...",https://ssl.cdn-redfin.com/photo/183/mbpaddedw...,Listed by Octavio Duarte •TREC #0616335 • SITE...,fbadbf86-3ee5-5100-a163-2acd162c43e5,17/04/2022 21:21:34
3,3439 NW 9th St,466995.0,"$466,995",USD,3439 NW 9th St,Redmond,OR,97756,US,44.292202,-121.178761,"At 1979 square feet, the Orchard Encore on lot...",2,4.0,"1,979","[{'Status': 'Pending'}, {'Time on Redfin': '12...",https://ssl.cdn-redfin.com/photo/199/mbpaddedw...,Listed by Lexxye Haggard • New Home Star Oreg...,ba379e0c-5517-56a5-bd93-6e9620577ebc,17/04/2022 21:21:35
4,1545 N Larrabee St Unit 2N,489900.0,"$489,900",USD,1545 N Larrabee St Unit 2N,Chicago,IL,60610,US,41.910518,-87.643162,Spacious Two Bedroom Condo residing in an Inti...,2,2.0,"1,550","[{'Status': 'Active'}, {'Time on Redfin': '17 ...",https://ssl.cdn-redfin.com/photo/68/mbpaddedwi...,Listed by Kieran Conlon • Compass,c22132b1-1809-5428-bd6c-59de7edf3dff,17/04/2022 21:21:35
5,3760 Bear Tooth Ln,1175000.0,"$1,175,000",USD,3760 Bear Tooth Ln,Wildwood,MO,63069,US,38.553768,-90.708614,Look no further! This custom-built 1.5 story s...,6,4.0,"5,231","[{'Status': 'Pending'}, {'Time on Redfin': '3 ...",https://ssl.cdn-redfin.com/photo/156/mbpaddedw...,Listed by Kristi & JT Monschein • Berkshire H...,01b99302-730a-567d-a855-759fa618201f,17/04/2022 21:21:35
6,569 77th St,1299000.0,"$1,299,000",USD,569 77th St,Bay Ridge,NY,11209,US,40.627067,-74.021407,"Great home in desirable area, close to all. la...",1.5,3.0,"1,842","[{'Status': 'Active'}, {'Time on Redfin': '91 ...",https://ssl.cdn-redfin.com/photo/269/mbpaddedw...,Listing by Emily Cherson • Park Avenue Realty LB,b1fb000d-92fe-5b48-b75c-e87b979a398b,17/04/2022 21:21:36
7,734 Collins Run,484900.0,"$484,900",USD,734 Collins Run,Mc Minnville,TN,37110,US,35.637553,-85.692484,A View of the mountains and an amazing custom ...,2.5,3.0,"2,238","[{'Status': 'Active Under Contract'}, {'Proper...",https://ssl.cdn-redfin.com/photo/145/mbpaddedw...,Listed by Lynne Cole • Kirby Real Estate,f923c67f-c954-5c91-a365-e4132799fe43,17/04/2022 21:21:36
8,1064 Taylors Island Rd,10400000.0,"$10,400,000",USD,1064 Taylors Island Rd,Madison,MD,21648,US,38.505091,-76.235219,Presenting Black Pearl Lodge and Farms. Locate...,-,NaN,-,"[{'Status': 'Active'}, {'Time on Redfin': '108...",https://ssl.cdn-redfin.com/photo/235/mbpaddedw...,Listed by Benjamin Alder • The Land Group,2570db96-7c3e-52d4-868a-82e9e6c00fc7,17/04/2022 21:21:36
9,431 North St,239900.0,"$239,900",USD,431 North St,Milford,DE,19963,US,38.918150,-75.431189,* * New Construction * * Make this 3 bedro...,2.5,3.0,"1,571","[{'Status': 'Pending'}, {'Time on Redfin': '29...",NaN,Listed by Rosezette Dennis • Keller Williams ...,5b3b4504-55e1-51a0-89cd-887c649e7162,17/04/2022 21:21:37

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              39 non-null     object
 1   price             38 non-null     float64
 2   formatted_price   37 non-null     object
 3   currency          39 non-null     object
 4   address           39 non-null     object
 5   locality          39 non-null     object
 6   region            39 non-null     object
 7   postal_code       39 non-null     int64
 8   country           39 non-null     object
 9   latitude          36 non-null     float64
 10  longitude         36 non-null     float64
 11  description       38 non-null     object
 12  baths             39 non-null     object
 13  beds              30 non-null     float64
 14  sqft              39 non-null     object
 15  property_details  39 non-null     object
 16  images            28 non-null     object
 17  listed_by         37 non-null     object
 18  uniq_id           39 non-null     object
 19  scraped_at        39 non-null     object
dtypes: float64(4), int64(1), object(15)
memory usage: 3.9+ KB

In [86]:
df['baths'].value_counts()

-      11
2      10
1       4
2.5     4
3       3
1.5     3
5       2
6       1
4       1
Name: baths, dtype: int64

In [87]:
df['baths']=df['baths'].str.replace('-','NaN')

In [88]:
df['baths']=df['baths'].astype(float)

In [89]:
df['baths'].value_counts()

2.0    10
1.0     4
2.5     4
3.0     3
1.5     3
5.0     2
6.0     1
4.0     1
Name: baths, dtype: int64

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              39 non-null     object
 1   price             38 non-null     float64
 2   formatted_price   37 non-null     object
 3   currency          39 non-null     object
 4   address           39 non-null     object
 5   locality          39 non-null     object
 6   region            39 non-null     object
 7   postal_code       39 non-null     int64
 8   country           39 non-null     object
 9   latitude          36 non-null     float64
 10  longitude         36 non-null     float64
 11  description       38 non-null     object
 12  baths             28 non-null     float64
 13  beds              30 non-null     float64
 14  sqft              39 non-null     object
 15  property_details  39 non-null     object
 16  images            28 non-null     object
 17  listed_by         37 non-null     object
 18  uniq_id           39 non-null     object
 19  scraped_at        39 non-null     object
dtypes: float64(5), int64(1), object(14)
memory usage: 4.0+ KB

In [91]:
df.head()

,name,price,formatted_price,currency,address,locality,region,postal_code,country,latitude,longitude,description,baths,beds,sqft,property_details,images,listed_by,uniq_id,scraped_at
0,Hickory Hill Rd,40000.0,"$40,000",USD,Hickory Hill Rd,Eastover,SC,29044,US,33.867386,-80.681014,This 4.13 ac of wooded land is ready for you b...,NaN,NaN,-,"[{'Status': 'Active'}, {'Time on Redfin': '230...",NaN,Listed by Glen Levine • Keller Williams Columbia,efb7c6cf-dbb1-5e4e-9028-32bc46800252,17/04/2022 21:21:33
1,147-35 38th Ave Unit B37,415000.0,"$415,000",USD,147-35 38th Ave Unit B37,Flushing,NY,11354,US,40.764069,-73.817481,Large and Sunny Two Bedroom Coop Apartment in ...,1.0,2.0,-,"[{'Status': 'Active'}, {'Time on Redfin': '201...",https://ssl.cdn-redfin.com/photo/269/mbpaddedw...,Listing by Nadine Persaud • All Area Brokerag...,e10a3655-1719-57e7-8d9d-984c82584c73,17/04/2022 21:21:34
2,1024 Indigo Sky St,240950.0,"$240,950",USD,1024 Indigo Sky St,El Paso,TX,79928,US,31.714074,-106.206967,"The Myrtle by Saratoga Homes. A 1 Story, 4 Bed...",3.0,4.0,"1,687","[{'Status': 'Pending'}, {'Time on Redfin': '13...",https://ssl.cdn-redfin.com/photo/183/mbpaddedw...,Listed by Octavio Duarte •TREC #0616335 • SITE...,fbadbf86-3ee5-5100-a163-2acd162c43e5,17/04/2022 21:21:34
3,3439 NW 9th St,466995.0,"$466,995",USD,3439 NW 9th St,Redmond,OR,97756,US,44.292202,-121.178761,"At 1979 square feet, the Orchard Encore on lot...",2.0,4.0,"1,979","[{'Status': 'Pending'}, {'Time on Redfin': '12...",https://ssl.cdn-redfin.com/photo/199/mbpaddedw...,Listed by Lexxye Haggard • New Home Star Oreg...,ba379e0c-5517-56a5-bd93-6e9620577ebc,17/04/2022 21:21:35
4,1545 N Larrabee St Unit 2N,489900.0,"$489,900",USD,1545 N Larrabee St Unit 2N,Chicago,IL,60610,US,41.910518,-87.643162,Spacious Two Bedroom Condo residing in an Inti...,2.0,2.0,"1,550","[{'Status': 'Active'}, {'Time on Redfin': '17 ...",https://ssl.cdn-redfin.com/photo/68/mbpaddedwi...,Listed by Kieran Conlon • Compass,c22132b1-1809-5428-bd6c-59de7edf3dff,17/04/2022 21:21:35